### ISSUE TITLE
Error NG Serve client --disable-hst-check --host 0.0.0.0

### ISSUE THREAD

**Issue by futhgar** [psychowood/ghostfolio-docker#5]
I'm on the last step after docker-compose up -d I get an error and "exited: on ghostfolio_base_1.

![image](https://github.com/psychowood/ghostfolio-docker/assets/51002668/29937a8f-8938-4af5-9046-d535f7b1d409)

$ ng serve client --disable-host-check --host 0.0.0.0
Error: This command is not available when running the Angular CLI outside a workspace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by psychowood** [comment]
No need to use this repo anymore, considering Ghostfolio has its official image now
